### ISSUE TITLE
Error: getTokens Error

### ISSUE THREAD

**Issue by brianibok** [spanishdict/example-dfp-line-item-generator#32]
Hi All,

Trying to create an order using the script and everything works fine up until I run the create order command and get the error below:

getTokens Error invalid_grant
.../example-dfp-line-item-generator/node_modules/node-google-dfp/lib/DfpUser.js:69
      throw error;
      ^

Any ideas?

**Comment by JuanCaicedo** [comment]
Hi @brianibok, I think this problem has to do with authentication. 

I found a couple links that could be useful:
- https://groups.google.com/forum/#!topic/google-doubleclick-for-publishers-api/ogoaTEIJeCI
- http://stackoverflow.com/questions/34027713/google-oauth2-access-token-invalid-grant

In the future, I think this type of question might be better fit for either the [double click for publishers support forum](https://productforums.google.com/forum/#!forum/dfp), or for stackoverflow, since I don't think it's a problem with this library. 

Best of luck! 😃
